import { WeatherData } from "./types";
import { mapWeatherCode } from "./utils";
export const dummieData: WeatherData[] = [
  {
    date: 1,
    highTemp: 39.4,
    lowTemp: 28.6,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 2,
    highTemp: 41.5,
    lowTemp: 28.3,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 3,
    highTemp: 59.8,
    lowTemp: 39.8,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 4,
    highTemp: 58,
    lowTemp: 37.7,
    weather: mapWeatherCode(63),
    windSpeed: 12,
  },
  {
    date: 5,
    highTemp: 42.4,
    lowTemp: 30.8,
    weather: mapWeatherCode(71),
    windSpeed: 12,
  },
  {
    date: 6,
    highTemp: 42.5,
    lowTemp: 29.4,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 7,
    highTemp: 50.8,
    lowTemp: 36.6,
    weather: mapWeatherCode(63),
    windSpeed: 12,
  },
  {
    date: 8,
    highTemp: 55.4,
    lowTemp: 37.2,
    weather: mapWeatherCode(63),
    windSpeed: 12,
  },
  {
    date: 9,
    highTemp: 43.1,
    lowTemp: 30.1,
    weather: mapWeatherCode(2),
    windSpeed: 12,
  },
  {
    date: 10,
    highTemp: 40.9,
    lowTemp: 27.7,
    weather: mapWeatherCode(73),
    windSpeed: 12,
  },
  {
    date: 11,
    highTemp: 43.5,
    lowTemp: 33.7,
    weather: mapWeatherCode(51),
    windSpeed: 12,
  },
  {
    date: 12,
    highTemp: 38.5,
    lowTemp: 29.7,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 13,
    highTemp: 37.2,
    lowTemp: 27.1,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 14,
    highTemp: 37.3,
    lowTemp: 27.1,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 15,
    highTemp: 45.6,
    lowTemp: 30.5,
    weather: mapWeatherCode(71),
    windSpeed: 12,
  },
  {
    date: 16,
    highTemp: 39.3,
    lowTemp: 29.6,
    weather: mapWeatherCode(73),
    windSpeed: 12,
  },
  {
    date: 17,
    highTemp: 36.5,
    lowTemp: 27.7,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 18,
    highTemp: 32.6,
    lowTemp: 24.2,
    weather: mapWeatherCode(2),
    windSpeed: 12,
  },
  {
    date: 19,
    highTemp: 31.4,
    lowTemp: 23.4,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 20,
    highTemp: 31.9,
    lowTemp: 22.8,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 21,
    highTemp: 35.4,
    lowTemp: 23.8,
    weather: mapWeatherCode(0),
    windSpeed: 12,
  },
  {
    date: 22,
    highTemp: 35.5,
    lowTemp: 25.4,
    weather: mapWeatherCode(71),
    windSpeed: 12,
  },
  {
    date: 23,
    highTemp: 40.5,
    lowTemp: 29.3,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 24,
    highTemp: 46.7,
    lowTemp: 31.6,
    weather: mapWeatherCode(51),
    windSpeed: 12,
  },
  {
    date: 25,
    highTemp: 29.9,
    lowTemp: 24.3,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 26,
    highTemp: 24,
    lowTemp: 14,
    weather: mapWeatherCode(73),
    windSpeed: 12,
  },
  {
    date: 27,
    highTemp: 22,
    lowTemp: 9.3,
    weather: mapWeatherCode(0),
    windSpeed: 12,
  },
  {
    date: 28,
    highTemp: 31.4,
    lowTemp: 12.3,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 29,
    highTemp: 41.3,
    lowTemp: 29.2,
    weather: mapWeatherCode(71),
    windSpeed: 12,
  },
  {
    date: 30,
    highTemp: 43.1,
    lowTemp: 25.3,
    weather: mapWeatherCode(3),
    windSpeed: 12,
  },
  {
    date: 31,
    highTemp: 42.9,
    lowTemp: 29,
    weather: mapWeatherCode(51),
    windSpeed: 12,
  },
];
