import { WeatherData } from "@/lib/types";

export const dummyData: WeatherData[] = [
  {
    date: 1,
    highTemp: 79,
    lowTemp: 43,
    weather: "partlyCloudy",
    moonPhase: "waxingGibbous",
  },
  {
    date: 2,
    highTemp: 63,
    lowTemp: 35,
    weather: "sunny",
    moonPhase: "waxingGibbous",
  },
  {
    date: 3,
    highTemp: 56,
    lowTemp: 33,
    weather: "sunny",
    moonPhase: "waxingGibbous",
  },
  {
    date: 4,
    highTemp: 59,
    lowTemp: 45,
    weather: "partlyCloudy",
    moonPhase: "waxingGibbous",
  },
  {
    date: 5,
    highTemp: 75,
    lowTemp: 59,
    weather: "partlyCloudy",
    moonPhase: "full",
  },
  {
    date: 6,
    highTemp: 78,
    lowTemp: 59,
    weather: "partlyCloudy",
    moonPhase: "waningGibbous",
  },
  {
    date: 7,
    highTemp: 75,
    lowTemp: 44,
    weather: "partlyCloudy",
    moonPhase: "waningGibbous",
  },
  {
    date: 8,
    highTemp: 66,
    lowTemp: 44,
    weather: "partlyCloudy",
    moonPhase: "waningGibbous",
  },
  {
    date: 9,
    highTemp: 61,
    lowTemp: 40,
    weather: "partlyCloudy",
    moonPhase: "waningGibbous",
  },
  {
    date: 10,
    highTemp: 66,
    lowTemp: 54,
    weather: "rainy",
    moonPhase: "lastQuarter",
  },
  {
    date: 11,
    highTemp: 70,
    lowTemp: 47,
    weather: "rainy",
    moonPhase: "lastQuarter",
  },
  {
    date: 12,
    highTemp: 65,
    lowTemp: 45,
    weather: "partlyCloudy",
    moonPhase: "waningCrescent",
  },
  {
    date: 13,
    highTemp: 64,
    lowTemp: 48,
    weather: "partlyCloudy",
    moonPhase: "waningCrescent",
  },
  {
    date: 14,
    highTemp: 62,
    lowTemp: 44,
    weather: "rainy",
    moonPhase: "waningCrescent",
  },
  {
    date: 15,
    highTemp: 59,
    lowTemp: 39,
    weather: "rainy",
    moonPhase: "waningCrescent",
  },
  {
    date: 16,
    highTemp: 57,
    lowTemp: 41,
    weather: "partlyCloudy",
    moonPhase: "new",
  },
  {
    date: 17,
    highTemp: 59,
    lowTemp: 38,
    weather: "partlyCloudy",
    moonPhase: "new",
  },
  {
    date: 18,
    highTemp: 58,
    lowTemp: 42,
    weather: "partlyCloudy",
    moonPhase: "new",
  },
  {
    date: 19,
    highTemp: 62,
    lowTemp: 43,
    weather: "rainy",
    moonPhase: "waxingCrescent",
  },
  {
    date: 20,
    highTemp: 54,
    lowTemp: 31,
    weather: "sunny",
    moonPhase: "waxingCrescent",
  },
  {
    date: 21,
    highTemp: 54,
    lowTemp: 31,
    weather: "sunny",
    moonPhase: "waxingCrescent",
  },
  {
    date: 22,
    highTemp: 54,
    lowTemp: 31,
    weather: "sunny",
    moonPhase: "waxingCrescent",
  },
  {
    date: 23,
    highTemp: 53,
    lowTemp: 31,
    weather: "sunny",
    moonPhase: "firstQuarter",
  },
  {
    date: 24,
    highTemp: 53,
    lowTemp: 30,
    weather: "sunny",
    moonPhase: "waxingGibbous",
  },
  {
    date: 25,
    highTemp: 53,
    lowTemp: 30,
    weather: "sunny",
    moonPhase: "waxingGibbous",
  },
  {
    date: 26,
    highTemp: 52,
    lowTemp: 30,
    weather: "sunny",
    moonPhase: "waxingGibbous",
  },
  {
    date: 27,
    highTemp: 52,
    lowTemp: 30,
    weather: "sunny",
    moonPhase: "waxingGibbous",
  },
  {
    date: 28,
    highTemp: 52,
    lowTemp: 30,
    weather: "sunny",
    moonPhase: "waxingGibbous",
  },
  { date: 29, highTemp: 51, lowTemp: 29, weather: "sunny", moonPhase: "full" },
  { date: 30, highTemp: 51, lowTemp: 29, weather: "sunny", moonPhase: "full" },
];
